services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\A21glossary\:
    resource: '../Classes/*'

  WapplerSystems\A21glossary\EventListener\AfterCacheableContentIsGeneratedEventListener:
    tags:
      - name: event.listener
        identifier: 'a21glossary/content-modifier'
